### ISSUE TITLE
Elder seal is missing (weapon)

### ISSUE THREAD

**Issue by RayLuxembourg** [LartTyler/MHWDB-Docs#10]

**Comment by LartTyler** [comment]
Got it, thanks.

**Comment by LartTyler** [comment]
I see the problem. Elder seal isn't listed anywhere on Kiranico, which is why it got missed. I think I can scrape it from the Monster Hunter Wikia pages ([this page](http://monsterhunter.wikia.com/wiki/MHW:_Great_Sword_Weapon_Tree), lists Elderseal as it's own column). That might actually work out perfectly, since I needed to write a scraper for the wikia anyway, to grab the weapon icons.

**Comment by LartTyler** [comment]
@RayLuxembourg Elderseal has been added for most weapons with [v1.5.4](https://github.com/LartTyler/MHWDB-Docs/releases/tag/1.5.4). I'm using the MHW Wikia as my source, but it doesn't have elderseal listed for all weapons. If you can find another source for elderseal values, I'll get to work on writing a scraper for it, but if not I'll just keep an eye on the wikia and add them when possible.

**Comment by RayLuxembourg** [comment]
@LartTyler not all weapons posses elder seal. the default value should be none or something.

**Comment by LartTyler** [comment]
I know not every weapon has elderseal, I meant that the place I'm scraping the values from has no values listed at all for some weapon types. For example, I know that the Nergal insect glaives have high elderseal, but it isn't listed anywhere on the Wikia. I'm going to work on a way to add them manually without messing up the rest of the scraping system, but I wanted to get 1.5.4 out before that, so there was at least some elderseal values for you to work with.

I haven't updated the docs yet, but elderseal is in the field `attributes.elderseal` for weapons that have an elderseal value, and will be one of the following strings: "low", "average", or "high".

**Comment by RayLuxembourg** [comment]
If you want I can build a Data management system for you to edit data easily. 
You will only need to provide valid API for POST,PUT

**Comment by LartTyler** [comment]
I appreciate the offer, but no thank you. The API is intentionally read-only, and any change to the data in the API is actually done at scrape time, and then merged into the production database when a new version is deployed.

I should have elderseal values added soon for all weapons except for insect glaives, light bowguns, and heavy bowguns, since I couldn't find those anywhere online. If you've got the spare time and you feel like helping with those last few weapon types, that'd be awesome, but if not I'll look them up in game and get those into the API sometime this week.

**Comment by LartTyler** [comment]
Elderseal values for hunting horns, gunlances, and switch axes is now available in the API. The last 3 (insect glaives, light bowguns, and heavy bowguns) will be added soon.

**Comment by RayLuxembourg** [comment]
@LartTyler have you pushed the changes?
currently not getting elderseal nowhere.

**Comment by LartTyler** [comment]
I know I pushed it, and I verified that it was available in production, but I think the last update may have messed something up. Give me a bit to look into it.

**Comment by LartTyler** [comment]
@RayLuxembourg It looks like v1.6.1 had accidentally removed elderseal values across the board. As of [v1.6.2](https://github.com/LartTyler/MHWDB-Docs/releases/tag/1.6.2), this has been fixed.

**Comment by LartTyler** [comment]
ALL elderseal values are now (finally!) available with [v1.13.0](https://github.com/LartTyler/MHWDB-Docs/releases/tag/1.13.0).
