### ISSUE TITLE
Weapons decoration slots && Armor decoration slots (weird data)

### ISSUE THREAD

**Issue by RayLuxembourg** [LartTyler/MHWDB-Docs#13]
This shouldn't be living inside attributes well at least not like it is now.
More practical arrangement is
slots:[
{rank:1},
{rank:2},
{rank:3}
]
if array empty , item has no decoration slots.
else iterate array and do what you want.
currently it's really weird.
I need to arrange assets according to the data but have to write weird logic to do so.
<img width="512" alt="screen shot 2018-04-13 at 22 32 30" src="https://user-images.githubusercontent.com/15327989/38754450-98860be2-3f6a-11e8-9d19-19951b0c182c.png">

**Comment by kclay** [comment]
Agree this would be a good change, I actually have something like this for my needs.

**Comment by RayLuxembourg** [comment]
@kclay what are you developing :O?

**Comment by LartTyler** [comment]
I need to pick a format that works best with how the API is set up, but I'm thinking of changing slots to something like this:

```json
{
    "slots": [
        1,
        1
    ]
}
```

```json
{
    "slots": [
        2,
    ]
}
```

Basically, just an array with 0 to 3 elements, each one an integer representing the rank of the slot.

**Comment by kclay** [comment]
@LartTyler I sorta like what @RayLuxembourg proposed. It allows easy attaching on other properties without any data remodeling. For instance, if I'm making a build simulator I would want my builder to show what slots I have and what deco is set on that slot. This can be achieved by simply doing 

```js
{
"slots":[
   {rank:1,deco:<decoId>}
   ]
}
```

Not really a big deal as we can always remodel the data client side, but it seems this would solve two use cases (mines and OP). Now as for the querying of this data. It looks like you are using mongodb Or does Mysql now allow json query been a while since I've used MySQL, saw you stated it on reddit.  But with mongo I think you could do ```slots:{$in:{rank:1}}```? Not sure if this is a valid query or what performance cost it may have.

**Comment by kclay** [comment]
Nice library fooled me. Can't wait for #15 its really the only piece I'm missing right now for this builder. So for now I'm going to work on the searching and computing all the stats values.

**Comment by cheng1994** [comment]
@LartTyler So to clarify you plan on moving slots to a separate key in each armor and weapon piece and then follow it with children with key rank? I'd like to prep my application for the change since I've already made slotsRank1 work in my case. But I'm more than open for improvements. 

Also if anyone wants to take a look my application is at [The Research Commision](https://theresearchcommission.com/) its still a work in progress

**Comment by LartTyler** [comment]
@cheng1994 Sorry, reading over that again I'm realizing that my plan wasn't very clear.

Any change I make to an existing endpoint will be backwards compatible, with a deprecation notice in the changelog of the release detailing which release or on what date the old information will be removed.

As far as this change goes, I'm going to leave the `slotsRank#` fields as they are in the `attributes` field. I'll be adding a `slots` field to the object itself that'll include the slot rank information, which should make (for example) armor objects look something like this (some fields are removed from the example below  for brevity).

```json
{
  "id": 505,
  "name": "Diablos Nero Coil Beta",
  "attributes": {
    "slotsRank2": 1
  },
  "slots": [
    {
      "rank": 2
    }
  ]
}
```

So in your case, your application can continue to function as is, giving you time to make the change over to the new format.

**Comment by LartTyler** [comment]
Slot information has been migrated to the new format we discussed in [v1.8.0](https://github.com/LartTyler/MHWDB-Docs/releases/tag/1.8.0).
