### ISSUE TITLE
(Missing-Data) Armor Sets

### ISSUE THREAD

**Issue by RayLuxembourg** [LartTyler/MHWDB-Docs#20]
Not sure if some of the data was mentioned here before, so i'll add this to make sure.
Currently I have this view I am working on
<img width="529" alt="screen shot 2018-04-18 at 20 21 18" src="https://user-images.githubusercontent.com/15327989/38947820-90baf320-4346-11e8-8db8-3452ea06c5f5.png">

Missing data list to complete the view:
Total craft cost,
total resistance + defense,
Full set skills,
Detailed set bonus skill

that would be all i know for now.
I know assets are in progress so i am not including them in the list.

**Comment by LartTyler** [comment]
All of that information should be available in the API already. Retrieving an armor set includes all of the pieces in the set, so you should be able to calculate all of the information that you need.

For example, since I think you've mentioned that you're using Swift, if you wanted to get the total level of all the skills in the armor set, you could do something like this:

```swift
// armorSet = the decoded JSON from the API

var skills = [String: Int]();

for armor in armorSet.pieces {
	for skill in armor.skills {
		if skills[skill.skillName] == nil {
			skills[skill.skillName] = 0;
		}

		skills[skill.skillName] += skill.level;
	}
}
```


As far as set bonuses go, they are available as of [v1.7.0](https://github.com/LartTyler/MHWDB-Docs/releases/tag/1.7.0). The information is being scraped from fextralife, and may be incomplete, but should be there for the most part ([click here](https://mhw-db.com/armor/sets/126) and check out the `bonus` field for an example).
